name: "Teardown esp-idf devcontainer"
description: |
  Stop and remove the esp-idf devcontainer.
runs:
  using: "composite"
  steps:
    - name: Teardown esp-idf devcontainer
      shell: bash
      id: teardown
      run: |
        container_name=esp-devc-${{ github.run_id }}
        docker stop -t 1 ${container_name} || true
        docker rm ${container_name} || true
