name: "ESP Firmware Create Firmware Package Action"
description: |
  Create a firmware package file. Build step must have been run before this action.

inputs:
  article-group:
    description: "Article group for the firmware package, e.g. s103"
    required: true
  hwname:
    description: "Hardware name for the firmware package, e.g. sio02"
    required: true
  major-revision:
    description: "Major revision for the hwname, e.g. 2"
    required: true
  output-file-suffix:
    description: "Suffix to append to the output firmware package file (e.g. -staging)"
    required: true
  app-binary:
    description: "Path to the application binary"
    required: true
  variant:
    description: "Firmware variant name, e.g. default"
    required: true
  version:
    description: "Version string, e.g. 1.0.0"
    required: true

runs:
  using: "composite"
  steps:
    - name: Package
      shell: bash
      id: fwpkg
      run: |
        ${{ github.action_path }}/io4edge-make-fwpkg.sh \
          "${{ inputs.app-binary }}" \
          "${{ inputs.article-group }}-${{ inputs.hwname }}" \
          "${{ inputs.variant }}" \
          "${{ inputs.version }}" \
          "${{ inputs.major-revision }  }" \
          "${{ inputs.output-file-suffix }}"

outputs:
  fwpkg:
    description: "Filename of the created firmware package file"
    value: ${{ steps.fwpkg.outputs.fwpkg }}