name: "ESP Firmware Build Action"
description: "Build ESP firmware using the devcontainer used in the project"
inputs:
  devcontainer-image:
    description: "Devcontainer image to use for build"
    required: true
  app-build-command:
    description: "command to execute in container to build app (e.g. idf.py build or make build-secure)"
    required: true
  build-dfu:
    description: "Whether to build dfu binary"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Get project and filename
      shell: bash
      id: identify
      env:
        EVENT_NAME: ${{ github.event_name }}
      run: |
        project=$(grep PKG_FIRMWARE_NAME fw-package.env | cut -f 2 -d =)
        echo "project=$(echo ${project})" >> $GITHUB_OUTPUT

    - name: Build App
      shell: bash
      id: build
      run: |
        ${{ github.action_path }}/../run_in_devcontainer/setup.sh "${{ inputs.devcontainer-image}}"
        ${{ github.action_path }}/../run_in_devcontainer/run.sh "${{ inputs.app-build-command }}"  

outputs:
  project-name:
    description: "Project name"
    value: ${{ steps.identify.outputs.project }}
  version:
    description: "App version"
    value: ${{ steps.build.outputs.version }}
  app-file:
    description: "App file without path (with project name and version)"
    value: ${{ steps.build.outputs.app-file }}
  app-file-path:
    description: "App file path"
    value: ${{ steps.build.outputs.app-file-path }}
  build-dir:
    description: "Build directory"
    value: ${{ steps.build.outputs.build-dir }}
  dfu-file:
    description: "DFU file path"
    value: ${{ steps.build.outputs.dfu-file }}