name: "Setup hostusr in devcontainer"
description: |
  This action sets up a user named 'hostusr' in the devcontainer with the same UID and GID as the host user.
  This allows for proper file permissions when accessing mounted volumes.
runs:
  using: "composite"
  steps:
    - name: Setup hostusr
      id: setup_hostusr
      shell: bash
      run: |
          HUID=$(stat -c '%u' "$GITHUB_WORKSPACE")
          HGID=$(stat -c '%g' "$GITHUB_WORKSPACE")
          echo "Using host UID:GID = ${HUID}:${HGID}"

          getent group "${HGID}" >/dev/null || groupadd -g "$HGID" hostgrp
          id -u hostusr >/dev/null 2>&1 || useradd -M -s /bin/bash -u "$HUID" -g "$HGID" hostusr
          mkdir -p /home/hostusr && chown hostusr:hostgrp /home/hostusr