name: "Get Builder Image"
description: |
  Get the Docker image used for building the ESP firmware from .devcontainer/devcontainer.json"
  write the image name to GITHUB_OUTPUT builder-image variable
runs:
  using: "composite"
  steps:
    - name: Get Builder Image
      shell: bash
      id: getbuilder
      # Build firmware using same docker image as used in devcontainer or gitpod to have exactly same environment as for local builds
      run: |
        if [ -f .devcontainer/devcontainer.json ]; then
            builder_image=$(jq -r '.image' .devcontainer/devcontainer.json)
            echo "devcontainer.json exists, builder image is $builder_image"
            echo "builder-image=$builder_image" >> "$GITHUB_OUTPUT"
        else
            echo "No devcontainer.json found, exiting"
            exit 1
        fi
outputs:
  builder-image:
    description: "Docker image name"
    value: ${{ steps.getbuilder.outputs.builder-image }}