name: ESP32 Secure Bootloader Workflow

on:
  workflow_call:
    # inputs:
    #   firmware_signing_azure_subscription_id:
    #     required: true
    #     type: string
    #   firmware_signing_azure_tenant_id:
    #     required: true
    #     type: string
    #   firmware_signing_azure_app_id:
    #     required: true
    #     type: string
    #   firmware_signing_azure_dev_vault_name:
    #     required: true
    #     type: string
    #   firmware_signing_azure_prod_vault_name:
    #     required: true
    #     type: string
    #   firmware_signing_azure_dev_key_id_base:
    #     description: "The base ID for the development key used for signing firmware. e.g. https://firmware-key-test.vault.azure.net/keys/ci4rail-sio06-00-g"
    #     required: true
    #     type: string
    #   firmware_signing_azure_prod_key_id_base:
    #     description: "The base ID for the production key used for signing firmware. e.g. https://firmware-key-test.vault.azure.net/keys/ci4rail-sio06-00-g"
    #     required: true
    #     type: string
    #   num_signing_keys:
    #     required: true
    #     type: number

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ci4rail/fw_esp-action/actions/build_bootloader@v10
      with:
        repository: ci4rail/fw_esp-action
        # this context is available in reusable workflows
        ref: ${{ github.workflow_sha }}