name: ESP32 Secure App Workflow

permissions:
  id-token: write # required for OIDC
  contents: read

on:
  workflow_call:
    inputs:
      firmware_signing_azure_subscription_id:
        required: true
        type: string
      firmware_signing_azure_tenant_id:
        required: true
        type: string
      firmware_signing_azure_dev_app_id:
        required: true
        type: string
      firmware_signing_azure_dev_key_id:
        description: "ID for the development key used for signing firmware. e.g. https://firmware-key-test.vault.azure.net/keys/ci4rail-sio06-00-g0"
        required: true
        type: string
      firmware_signing_azure_prod_app_id:
        required: true
        type: string
      firmware_signing_azure_prod_key_id:
        description: "ID for the production key used for signing firmware. e.g. https://vault-firmware-signing.vault.azure.net/keys/ci4rail-sio06-00-g0"
        required: true
        type: string
      build-dfu:
        description: "Whether to build dfu binary"
        required: false
        type: boolean
        default: false
      teststation-broker:
        description: "IP:Port of MQTT broker where test station listens to"
        type: string
        required: true
      teststation-master-topic:
        description: "teststation request is published to <master-topic>/request"
        required: false
        type: string
        default: "teststation"
      teststation-request-timeout:
        description: "Time in seconds to wait for teststation to become available"
        required: false
        type: number
        default: 3600
      test-name:
        description: |
          Name of the test to execute (must match an entry in the test schedulers config file)
          If empty, skip test execution
        type: string
        required: true
      test-device-name:
        description: "Device id as listed in test schedulers config file to run the test on test station"
        type: string
        required: true
      
    secrets:
      access-token:
        description: "Personal access token for private repos"
        required: true
      tailscale-key:
        description: "a reusable tailscale key"
        required: true
      minio-access-key:
        description: "Access key for minio"
        required: true
      minio-secret-key:
        description: "Secret key for minio"
        required: true

jobs:
  # execute steps directly in runner
  get_builder:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.access-token }}
      - name: Get builder image
        id: get_builder
        uses: ci4rail/fw_esp-action/actions/get_builder_image@v10
    outputs:
      builder-image: ${{ steps.get_builder.outputs.builder-image }}

  # execute steps in devcontainer
  build:
    needs: get_builder
    runs-on: [self-hosted, linux, x64]

    outputs:
      project-name: ${{ steps.build_app.outputs.project-name }}
      version: ${{ steps.build_app.outputs.version }}
      app-file: ${{ steps.build_app.outputs.app-file }}

    steps:
      - name: Install AZ CLI
        shell: bash
        run: |
          if ! command -v az &> /dev/null; then
              echo "Azure CLI not found. Installing..." >&2
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          else
              echo "Azure CLI is already installed." >&2
          fi

      - name: build
        shell: bash
        run: |
          docker run -u $(id -u):$(id -g) --rm -v $PWD:/workspace -w /workspace \
            ${{ needs.get_builder.outputs.builder-image }} bash -c "source /opt/esp/idf/export.sh && ls -l && pwd && make build-secure"